### ISSUE TITLE
Incompatible with Netbox v2.5

### ISSUE THREAD

**Issue by adriankus** [bashioo/netbox_topology#1]
The new interface connection schema seems to have broken this add-on. A shame, I thought it was great! Should have been baked into Netbox main branch.

**Comment by bashioo** [comment]
Hi, sorry for the late reply. I actually [tried](https://github.com/digitalocean/netbox/issues/1827) to propose it to be included but it got rejected.

Unfortunately, I left the company I developed this addon for 6+ month ago and I do not use Netbox at my new job at all, so I just cannot support this repository anymore. It looks like there are a number of active forks, with [this](https://github.com/NoOne-dev/netbox_topology) seems to be the active one. I'd suggest you trying to move to it because I would not be able to keep mine up to date with Netbox changes.

Sorry for inconvenience and thanks for using my project!
